### ISSUE TITLE
Tutorial Docker gives error about 4.1 version

### ISSUE THREAD

**Issue by econceptions** [wso2/samples-apim#118]
**Description:**
manifest for wso2/wso2am:4.1.0 not found

**Suggested Labels:**
Update repository to fix this issue as this image is not found.

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by AlbertoCanoD** [comment]
The Docker Image for version 4.1.0 does not exist, you can use the latest or the 4.0.0(the latest right now). 

https://hub.docker.com/r/wso2/wso2am
