### ISSUE TITLE
Support for v4.0.0

### ISSUE THREAD

**Issue by bmonteiro** [wso2/samples-apim#32]
The Custom JWT works for APIM v4.0.0 ?

getting all the time =>  

```org.wso2.carbon.apimgt.gateway.handlers.security.jwt.JWTValidator.<init>(JWTValidator.java:108) ~[org.wso2.carbon.apimgt.gateway_9.0.174.jar:?]```

**Comment by MohaLaD** [comment]
any solution please ? 

same problem i guess, i followed the doc : [https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway/#jwt-generation-configuration-details](url)
i have this error when i start the server with `sh [WSOHOME]/bin/api-manager.sh`:

`ERROR - APIKeyMgtDataHolder Cannot find the class 
org.wso2.carbon.test.CustomTokenGeneratorjava.lang.ClassNotFoundException: org.wso2.carbon.test.CustomTokenGenerator cannot be found by org.wso2.carbon.apimgt.impl_9.0.174`
