### ISSUE TITLE
the solution pack does not start properly 

### ISSUE THREAD

**Issue by Nuwan-Walisundara** [wso2/samples-apim#51]
**Description:**
checkout the repo and start the compose but fail with retry. following are the logs

apim-tutorial-si-runtime-1       | [2022-03-09 05:46:57,650]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 Streaming Integrator started in 17.878 sec
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-api-manager-1      | Killed
apim-tutorial-api-manager-1 exited with code 0
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | Retrying after  5 s...

**Related Issues:**

**Comment by haydursek** [comment]
Same Issue, this doesn't work. Downloaded the repo and ran docker-compose, and it just fails to start.

`
apim-tutorial-scripts-1          | Retrying after  5 s...
apim-tutorial-scripts-1          | nc: bad address 'api-manager
`
